#development:
#  adapter: mysql2
#  encoding: utf8
#  reconnect: false
#  database: frontend_developer_test_development
#  pool: 5
#  username: root
#  password: root
#  socket: /var/run/mysqld/mysqld.sock
#  host: localhost
#  port: 3306

development:
 adapter: sqlite3
 database: db/development.sqlite3
 pool: 5
 timeout: 5000